# Generated by Django 5.2.17 on 2026-08-30 12:58

import django.db.models.deletion
from datetime import timedelta

from django.db import migrations, models
from django.utils import timezone


def grant_demo_to_existing(apps, schema_editor):
    Company = apps.get_model("hub", "Company")
    BeatPackage = apps.get_model("hub", "BeatPackage")
    ends = timezone.now() + timedelta(days=15)
    for company in Company.objects.all():
        if not company.trial_ends_at:
            company.trial_ends_at = ends
            company.save(update_fields=["trial_ends_at"])
        if not BeatPackage.objects.filter(company=company, kind="demo").exists():
            BeatPackage.objects.create(company=company, beats=10000, kind="demo")


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BeatPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beats', models.PositiveIntegerField()),
                ('kind', models.CharField(choices=[('demo', 'Demo'), ('purchase', 'Compra')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='hub.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(grant_demo_to_existing, migrations.RunPython.noop),
    ]
